version: 2
updates:
  # Maintain dependencies for go
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      go-minor-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      actions-minor-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
